// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package routes

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "quark-client/web/components"

func Login_Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n\t// page script starts\n\tconst handleLoginFormSubmit = () => {\n\t\tconst loginButton = document.getElementById(\"loginButton\")\n\t\tloginButton.innerHTML = `<span class=\"loading loading-spinner loading-lg\"></span>`\n\t}\n\tdocument.body.addEventListener(\"htmx:afterRequest\", (event) => {\n\t\tconst loginButton = document.getElementById(\"loginButton\")\n\t\tloginButton.innerHTML = \"Login\"\n\t\tconst res = JSON.parse(event.detail.xhr.response)\n\t\tif (res.status_code != \"PASS_LGN\") {\n\t\t\tdocument.body.insertAdjacentHTML('beforeend', res.toast);\n\t\t\tsetTimeout(() => {\n\t\t\t\tdocument.getElementById(\"loginToast\").remove();\n\t\t\t}, 2000);\n\t\t}\n\t})\n\t// page script ends\n</script> <div class=\"flex flex-col items-center mt-[150px] gap-[20px]\"><div class=\"flex flex-col items-center gap-[15px]\"><h1 class=\"text-4xl\">Login</h1><p>Don't have an account? <a href=\"/register\" class=\"link link-primary\">Register</a></p></div><form hx-post=\"/auth/login\" hx-swap=\"none\" name=\"loginForm\" class=\"flex flex-col items-center gap-[15px] w-full\"><input name=\"username\" placeholder=\"Username\" autocomplete=\"off\" class=\"input border-neutral focus:outline-none focus:border-primary placeholder-base-200 w-full max-w-[250px]\"> <input name=\"password\" placeholder=\"Password\" autocomplete=\"off\" class=\"input border-neutral focus:outline-none focus:border-primary placeholder-base-200 w-full max-w-[250px]\"> <button hx-on:click=\"handleLoginFormSubmit()\" id=\"loginButton\" type=\"submit\" class=\"btn btn-primary w-full max-w-[180px]\">Login</button></form></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Base_HTML().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
